Add GHA workflow step to verify the buildpackage image
buildpacks/registry-index pull request #792
Opened 2020-11-05 20:21 UTC by jkutner

This uses the [Verify Buildpackage Action](https://github.com/buildpacks/github-actions#verify-buildpackage-action) to ensure the buildpackage being registered is a valid buildpackage OCI image and that it matches the `id` and `version` asserted by the registration request.

2020-11-06 00:00 UTC, nebhale approved these changes

2020-11-06 00:00 UTC, nebhale requested changes

2020-11-06 00:00 UTC, nebhale commented on .github/workflows/register-buildpack.yml
> +      - uses: docker://ghcr.io/buildpacks/actions/verify-buildpackage
```suggestion
      - uses: docker://ghcr.io/buildpacks/actions/verify-buildpackage:main
```

2020-11-06 00:02 UTC, nebhale commented on .github/workflows/register-buildpack.yml
> +      - uses: docker://ghcr.io/buildpacks/actions/verify-buildpackage
I might need to update all the docs in `buildpacks/github-actions` with this.  It's not intuitive that you need a version.

2020-11-06 02:28 UTC, jkutner commented
I'm going to set up a staging repo so we can smoke test changes like this before merging them.

2020-11-06 03:35 UTC, nebhale approved these changes

2020-11-09 15:33 UTC, elbandito approved these changes

2020-11-09 16:50 UTC, merged